### ISSUE TITLE
Is there any capacity to upgrade this to lmdb version 0.9.29?

### ISSUE THREAD

**Issue by stevorobs3** [lmdbjava/native#11]
Hey @benalexau 

I'm using the lmdb java package in a production setting, and believe I'm hitting the bug that has been addressed in a later version of the underlying lmdb code: https://github.com/LMDB/lmdb/commit/4b6154340c27d03592b8824646a3bc4eb7ab61f5

Is there any scope to bump the version here? Seems like the changes since 0.9.24 are quite minimal and mostly bug fixes like this one.

Thanks!

**Comment by stevorobs3** [comment]
Would be amazing if that change could also then get pushed to the corresponding lmdbjava project too

**Comment by benalexau** [comment]
I have updated LmdbJava Native to 0.9.29 and released it on Maven Central.

Issue https://github.com/lmdbjava/lmdbjava/issues/194 has been opened to update LmdbJava to use LmdbJava Native 0.9.29-1.

**Comment by stevorobs3** [comment]
thank you so much for this @benalexau
