### ISSUE TITLE
lmbdjava 0.8.3 requires glibc 2.27

### ISSUE THREAD

**Issue by wardle** [lmdbjava/native#14]
I believe binaries were compiled against glibc 2.17 in prior versions, but now 2.27 is required. This precludes using lmbdjava on 'current' AWS EC2 instances of Amazon Linux, as well as recent Centos/Redhat systems. I understand this affected lwgl lmdb as well, but their changelog mentions this "Linux: x64 shared libraries are now built with GCC 11.2 (up from GCC 7.5)
The minimum GLIBC version is now 2.17. (down from 2.27) (https://github.com/LWJGL/lwjgl3/issues/842)".

I don't quite know how the binaries are built, but perhaps the systems that are used in CI to do those builds have been upgraded inadvertently and so a requirement on a later glibc has been therefore propagated as a dependency for lmbdjava?

My current fix is to force a downgrade to 0.8.2 for my Linux deployments, while continuing to benefit from 0.8.3 for my Mac development on ARM.

**Comment by wardle** [comment]
For example, Amazon Linux currently use 2.26.. See [https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2](https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2)

I see references to GitHub updating their build systems so that recent builds are likely to require newer glibc versions. So I think this issue is simply the result of GitHub actions updating their systems.

None of this precludes users experiencing this issue from building from source themselves, obviously, so this issue could be closed on this basis, unless it is easy to configure GitHub actions to use an older Linux system for builds so as to maximise compatibility.

**Comment by benalexau** [comment]
Did you see https://github.com/lmdbjava/lmdbjava/issues/211?

Would using Amazon Linux 2022 as mentioned in the [AWS re:Post](https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2) question be feasible?

**Comment by wardle** [comment]
Thanks @benalexau - no sorry I hadn't seen that thread. 

I have an ancient Centos on an NHS server than can't be upgraded so I'll try this https://github.com/lmdbjava/lmdbjava/issues/211#issuecomment-1438389376 which looks like a very good idea. 

For my AWS deployments, I'll wait for the release of Amazon Linux 22 to GA as it should then be available via Lightsail, or I'll try to same trick as above. 

Thanks again.
