### ISSUE TITLE
JVM crash inside lmdbjava-native-library

### ISSUE THREAD

**Issue by scf37** [lmdbjava/native#2]
[hs_err_pid21318.log](https://github.com/lmdbjava/native/files/2265660/hs_err_pid21318.log)

Ubuntu 16.04 x86_64
Linux kaktus 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by benalexau** [comment]
Please log any issues in the [LmdbJava issue tracker](https://github.com/lmdbjava/lmdbjava).
