### ISSUE TITLE
Question - what MDB_MAXKEYSIZE gets used at compile?

### ISSUE THREAD

**Issue by er1c** [lmdbjava/native#3]
Hi, 

I did try to look, but I didn't get a satisfactory answer.  Are you setting the `-DMDB_MAXKEYSIZE=0` to change the default key limit from the 511?  As far as I could tell, no, it still has the default key size limit in the compiled libraries, but I thought I'd check.

It would be cool two have two different versions of the native automatically generated - one with no key size limit, and then the other with the defaults.

**Comment by benalexau** [comment]
> Are you setting the `-DMDB_MAXKEYSIZE=0` to change the default key limit from the 511?

No. We just run `make clean test` as shown in the [POM](https://github.com/lmdbjava/native/blob/master/linux-x86_64/pom.xml#L35).

> It would be cool two have two different versions of the native automatically generated - one with no key size limit, and then the other with the defaults.

The `mdb.c` contains the following documentation:

```c
	/**	@brief The max size of a key we can write, or 0 for computed max.
	 *
	 *	This macro should normally be left alone or set to 0.
	 *	Note that a database with big keys or dupsort data cannot be
	 *	reliably modified by a liblmdb which uses a smaller max.
	 *	The default is 511 for backwards compat, or 0 when #MDB_DEVEL.
	 *
	 *	Other values are allowed, for backwards compat.  However:
	 *	A value bigger than the computed max can break if you do not
	 *	know what you are doing, and liblmdb <= 0.9.10 can break when
	 *	modifying a DB with keys/dupsort data bigger than its max.
	 *
	 *	Data items in an #MDB_DUPSORT database are also limited to
	 *	this size, since they're actually keys of a sub-DB.  Keys and
	 *	#MDB_DUPSORT data items must fit on a node in a regular page.
	 */
#ifndef MDB_MAXKEYSIZE
#define MDB_MAXKEYSIZE	 ((MDB_DEVEL) ? 0 : 511)
#endif
```

I assume you mean LmdbJava providing two native libraries for each supported platform, one being compiled with the defaults (as it is now) and one being compiled with the computed maximum (ie setting the max key size to 0).

I am reluctant to do this for a few reasons:

* Increased complexity of the LmdbJava Native build project (eg extra classifiers or submodules), and to be honest it's already pretty complex with the various cross-compilations it has to do
* Additional JAR size caused through embedding six system libraries (2 versions for Linux, Mac and Windows)
* There are many LMDB compilation options and from a precedent perspective it would be difficult to decline future requests for a non-default property if we have previously added a non-default option
* Users would need to specify which specific system library to use and given it would be a system property (as `Library` statically loads this) it seems reasonable for users with advanced needs to just set the existing `lmdbjava.native.lib` system property to a user-provided library
* It increases the learning curve and user troubleshooting effort when people encounter unexpected results (eg "did I use the wrong native library, I tried it with both?")
* While LMDB is hugely flexible and there are undoubtedly use cases that would benefit from large keys, I've never personally come close to the 511 byte limit in any of my applications

A practical suggestion here would be for you to fork the LmdbJava Native project, adjust the compilation options as desired, and change the `groupId` to something else. Then you could publish it to Maven Central (like LmdbJava Native currently is) and users who need those particular compilation options would include that native project JAR in their application classpath.

I am happy to make changes to LmdbJava to better support the community using custom builds that are embedded inside other JARs. One proposal would be `Library` first attempts to load the library from a custom build resource name and only falls back to the default resource name if the custom build resource name is not found. For example with Linux we could first attempt to load `org/lmdbjava/CUSTOM-lmdbjava-native-linux-x86_64.so` before falling back to `org/lmdbjava/lmdbjava-native-linux-x86_64.so` etc. That way it would automatically support any third-party builds appearing in the classloader (even those not published to Maven Central).

**Comment by er1c** [comment]
Thanks for the thoughtful response.  We currently are using custom libraries.  The tedium of compiling them separately (and for us, is a manual process).  If you have no objections to forking/publishing as a separate groupId, then I will certainly pursue that.  I also just didn't want to do that if there would be some other more generic possibility.

**Comment by er1c** [comment]
As a side, side note, we also maintain https://github.com/eluvio/lmdb-je, I'm not sure if it would be worth the time/effort to simply consolidate the `ConcurrentNavigableMap` stuff to this project.  Is that interesting to you? Or want to keep the existing API as is?  (One option is to also investigate building a map ontop of the API you already have)

**Comment by benalexau** [comment]
> If you have no objections to forking/publishing as a separate groupId, then I will certainly pursue that.

I have no objections as it's just a pragmatic way for anyone to add their own specialised compilation options. I do wonder thought whether there might be a better way, like LmdbJava doing more classloader scanning to locate any native library defined outside the LmdbJava JAR and using that instead (ie not requiring the proposed `CUSTOM-` prefix). Then maybe a build matrix for the LmdbJava Native project (eg use a branch-specific Maven properties file to define the build options and differentiate them with a classifier). I don't have time to investigate this at present but it might be a more elegant solution over the long-term. I just don't want dozens of native libraries in the LmdbJava JAR and/or dozens of submodules in the LmdbJava Native project. If that can be avoided I'm fairly happy to add "reasonable" user-requested compilation options to a separate LmdbJava Native build output.

> We currently are using custom libraries.

Is the maximum key size the only custom setting you are using?

> I find it annoying they have it defaulted to 0 in the MDB_DEVEL mode, I have no idea what that means :)

Out of interest what is reported if you call `Env.getMaxKeySize()` and on which platform(s)?

**Comment by er1c** [comment]
```
scala> (new eluvio.lmdb.api.Env()).maxKeySize
Mar 04, 2019 5:57:16 PM eluvio.lmdb.api.Loader load
INFO: Successfully loaded LMDB library from /Users/eric/Work/lmdb-je/target/classes/lmdb-je/darwin_x86_64/liblmdb.so
res0: Int = 0
```

**Comment by benalexau** [comment]
>  Is that interesting to you? Or want to keep the existing API as is? (One option is to also investigate building a map ontop of the API you already have)

I would encourage you to raise a separate ticket so we could have a closer look (eg show some test / example code). The existing iterator support is one of the most complex parts of the project given its requirement to support so many key range types, so we'd need to ensure it doesn't get any more complex to maintain that code.


> We just set it to the 0.

I was hoping it would report a platform-specific maximum value but upon reading the C code I can see it's just reporting the compilation value. Are you using very large keys? Maybe it's worth asking on the OpenLDAP mailing list for clarification as to what setting it to 0 does?
