### ISSUE TITLE
ARM build targets

### ISSUE THREAD

**Issue by EternalDeiwos** [lmdbjava/native#4]
What are the chances of supporting Linux builds for `arm64-v8a` and `armeabi-v7a`?

**Comment by benalexau** [comment]
If it's a cross-compilation target supported via the current Travis build image I wouldn't mind supporting it. Feel free to take a look and submit a PR if this is of interest.

**Comment by EternalDeiwos** [comment]
I'll give it a try.

**Comment by EternalDeiwos** [comment]
So its definitely a valid cross-compilation target that can be built on linux (x86-64) using the Android NDK but I'm a bit too unfamiliar with Maven to configure it to actually use the cross-compiler...

Current attempts include making a copy of your windows-x86-64 folder and replacing the compiler in your `pom.xml`:

```
<environmentVariables>
    <CC>${env.NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang</CC>
    <AR>${env.NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar</AR>
</environmentVariables>
```

Any pointers or relevant documentation would be appreciated.

**Comment by benalexau** [comment]
You're on the right track. You'd need to copy the `windows-x86_64` directory to a new sibling directory, amend the `artifactId` and `name` elements, and make a reference to your newly-created directory in the project's super POM, `$GIT_WORK_TREE/pom.xml` (in the `modules` element, once for the `release-tag` and once for the `linux` profiles).

The `exec-maven-plugin` runs during the `compile` phase, which is fairly early on in the build process (see [Introduction to Lifecycle Phases](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) for details). We are using the `exec:exec` goal which is [fully documented here](http://www.mojohaus.org/exec-maven-plugin/exec-mojo.html). As shown we are running plain old `make -e clean all` and have set some environment variables as used by `make` or the compiler. 

Later on in the build the `copy-rename-maven-plugin` runs, specifically in the `process-classes` phase. That copies the library built by `make` into the `target` directory, giving it a DLL name as is customary in Windows.

Finally the `maven-jar-plugin` includes everything under `target/native` in the final JAR. This makes it compatible with pushing up to Maven Central and easily including in the classpath of Java applications.

The other key file is `$GIT_WORK_TREE/travis.yml`. In there you will need to ensure the required compiler is actually installed. That's the trial and error part. As shown we're currently using the `xenial` distribution. You can read the [Xenial Build Environment](https://docs.travis-ci.com/user/reference/xenial/) documentation for more details.

**Comment by benalexau** [comment]
Thanks for your work on this issue and PR. I have just merged it.
