### ISSUE TITLE
can i use lmdb in my clound database ?

### ISSUE THREAD

**Issue by ChinaXing** [lmdbjava/native#6]
we build distributed database, want to use lmdb as a locale kv engine.
is this compliant with lmdb's licence ?

**Comment by benalexau** [comment]
LMDB is licensed under the [OpenLDAP Public License](https://www.openldap.org/software/release/license.html). I note there are distributed databases shown in LMDB's list of [other projects](https://symas.com/lmdb/technical/) using it. While I am not a lawyer (and linking does not signify any endorsement) you can read a [third party summary](https://tldrlegal.com/license/openldap-public-license-v2.8-(oldap-2.8)) of what the license means. Naturally you should seek your own professional legal advice if you have any concerns or questions.
